var arr = [{label: "0x800027", value: "Folder"},
{label: "От составителя", value: "preface.html#author"},
{label: "Особенности терминологии", value: "preface.html#terms"},
{label: "Условные обозначения", value: "preface.html#legend"},
{label: "Благодарности", value: "preface.html#thanks"},
{label: "О языке DSL", value: "dsl.html#lang"},
{label: "О формате DSL", value: "dsl.html#format"},
{label: "Простой словарь DSL", value: "create.html#easy"},
{label: "Структурированный словарь DSL с форматированием", value: "create.html#cool"},
{label: "Рекомендуемые инструменты", value: "create.html#tools"},
{label: "Рекомендуемая литература", value: "create.html#books"},
{label: "Общие сведения", value: "dict.html#main"},
{label: "Наименование файлов словаря", value: "dict.html#names"},
{label: "Файл основного текста", value: "dict.html#dsl"},
{label: "Файл аннотации", value: "dict.html#ann"},
{label: "Иконка", value: "dict.html#bmp"},
{label: "Файл аббревиатур", value: "dict.html#abrv"},
{label: "Словарная статья", value: "entry.html#article"},
{label: "Заголовок статьи", value: "entry.html#headword"},
{label: "Тело статьи", value: "entry.html#body"},
{label: "Устройство тегов", value: "tag_system.html#main"},
{label: "Метасимволы и литералы", value: "tag_system.html#meta_lit"},
{label: "Общие замечания", value: "tag_system.html#comments"},
{label: "Ограничения формата DSL", value: "dsl.html#limit"},
{label: "Перечень тэгов и команд DSL", value: "tag_list.html"},
{label: "Тэг B", value: "tag_format.html#b"},
{label: "Тэг I", value: "tag_format.html#i"},
{label: "Тэг U", value: "tag_format.html#u"},
{label: "Тэг C", value: "tag_format.html#c"},
{label: "Тэг SUP", value: "tag_format.html#sup"},
{label: "Тэг SUB", value: "tag_format.html#sub"},
{label: "Тэг M", value: "tag_format.html#m"},
{label: "Тэг ударения", value: "tag_format.html#str"},
{label: "Команда ^", value: "tag_format.html#circ"},
{label: "Тэг P", value: "tag_struct.html#p"},
{label: "Тэг *", value: "tag_struct.html#ast"},
{label: "Команда @", value: "tag_struct.html#at"},
{label: "Тэг EX", value: "tag_handling.html#ex"},
{label: "Тэг COM", value: "tag_handling.html#com"},
{label: "Тэг TRN", value: "tag_handling.html#trn"},
{label: "Тэг !TRS", value: "tag_handling.html#trs"},
{label: "Тэг LANG", value: "tag_handling.html#lang"},
{label: "Изображения", value: "tag_mm.html#images"},
{label: "Звук", value: "tag_mm.html#sound"},
{label: "Видео", value: "tag_mm.html#movie"},
{label: "Тэг << >>", value: "tag_links.html#ref1"},
{label: "Тэг REF", value: "tag_links.html#ref2"},
{label: "Тэг URL", value: "tag_links.html#url"},
{label: "Тэг {{ }}", value: "tag_service.html#comm"},
{label: "Команда ( )", value: "tag_service.html#alt"},
{label: "Команда { }", value: "tag_service.html#unsort"},
{label: "Команда ~", value: "tag_service.html#tilde"},
{label: "Команда \\", value: "tag_service.html#backslash"},
{label: "Команда #", value: "tag_service.html#number"},
{label: "Общее описание", value: "directives.html#main"},
{label: "Директива #NAME", value: "directives.html#name"},
{label: "Директива #INDEX_LANGUAGE", value: "directives.html#index"},
{label: "Директива #CONTENTS_LANGUAGE", value: "directives.html#contents"},
{label: "Директива #SOURCE_CODE_PAGE", value: "directives.html#source"},
{label: "Директива #INCLUDE", value: "directives.html#include"},
{label: "Директива #LANGUAGE", value: "directives.html#lang"},
{label: "Графический интерфейс пользователя", value: "dsl_comp.html#gui"},
{label: "Отчёт об ошибках", value: "dsl_comp.html#syntax"},
{label: "Цветовая палитра DSL", value: "colors.html"},
{label: "Списки языков", value: "langs.html"},
{label: "Поиск и индексирование в Lingvo", value: "search.html"},
{label: "Виды файлов словарей в Lingvo", value: "var_dicts.html"},
{label: "Об использовании нестандартных пробелов", value: "spaces.html"},
{label: "Немного о лексикографии", value: "lexicography.html"},
{label: "Сводная таблица по истории развития синтаксиса языка DSL", value: "history.html#table"},
{label: "Lingvo 4.0", value: "lingvo4.html"},
{label: "Lingvo 5.0", value: "lingvo5.html"},
{label: "Lingvo 6.0", value: "lingvo6.html"},
{label: "Lingvo 6.5", value: "lingvo6_5.html"},
{label: "Lingvo 7.0", value: "lingvo7.html"},
{label: "Lingvo 8.0", value: "lingvo8.html"},
{label: "Lingvo 9.0", value: "lingvo9.html"},
{label: "Lingvo 10.0", value: "lingvo10.html"},
{label: "Lingvo 11.0", value: "lingvo11.html"},
{label: "Lingvo 12.0", value: "lingvo12.html"},
{label: "Lingvo x3 (14.0)", value: "lingvo14.html"},
{label: "Lingvo x5 (15.0)", value: "lingvo15.html"},
{label: "Lingvo x6 (16.0)", value: "lingvo16.html"},
{label: "!trs", value: "tag_handling.html#trs"},
{label: "#", value: "tag_service.html#number"},
{label: "#CONTENTS_LANGUAGE", value: "directives.html#contents"},
{label: "#ICON_FILE", value: "directives.html#icon"},
{label: "#INCLUDE", value: "directives.html#include"},
{label: "#INDEX_LANGUAGE", value: "directives.html#index"},
{label: "#LANGUAGE", value: "directives.html#lang"},
{label: "#NAME", value: "directives.html#name"},
{label: "#SOURCE_CODE_PAGE", value: "directives.html#source"},
{label: "<< >>", value: "tag_links.html#ref1"},
{label: "'", value: "tag_format.html#str"},
{label: "( )", value: "tag_service.html#alt"},
{label: "(", value: "tag_service.html#alt"},
{label: ")", value: "tag_service.html#alt"},
{label: "*", value: "tag_struct.html#ast"},
{label: "@", value: "tag_struct.html#at"},
{label: "\\", value: "tag_service.html#backslash"},
{label: "^", value: "tag_format.html#circ"},
{label: "aliceblue (оттенки)", value: "colors.html#white_hue"},
{label: "aliceblue", value: "tag_format.html#c"},
{label: "ANSI", value: "langs.html#ansi"},
{label: "antiquewhite (оттенки)", value: "colors.html#white_hue"},
{label: "antiquewhite", value: "tag_format.html#c"},
{label: "aqua (основные оттенки)", value: "colors.html#basic_hue"},
{label: "aqua", value: "tag_format.html#c"},
{label: "aquamarine (оттенки)", value: "colors.html#blue_hue"},
{label: "aquamarine", value: "tag_format.html#c"},
{label: "asf", value: "tag_mm.html#sound"},
{label: "audio", value: "tag_mm.html#sound"},
{label: "avi", value: "tag_mm.html#movie"},
{label: "azure (оттенки)", value: "colors.html#white_hue"},
{label: "azure", value: "tag_format.html#c"},
{label: "b", value: "tag_format.html#b"},
{label: "beige (оттенки)", value: "colors.html#white_hue"},
{label: "beige", value: "tag_format.html#c"},
{label: "bisque (оттенки)", value: "colors.html#brown_hue"},
{label: "bisque", value: "tag_format.html#c"},
{label: "bitmap", value: "tag_mm.html#images"},
{label: "black (основные оттенки)", value: "colors.html#basic_hue"},
{label: "black (оттенки)", value: "colors.html#gray_hue"},
{label: "blanchedalmond (оттенки)", value: "colors.html#brown_hue"},
{label: "blanchedalmond", value: "tag_format.html#c"},
{label: "blue (основные оттенки)", value: "colors.html#basic_hue"},
{label: "blue (оттенки)", value: "colors.html#blue_hue"},
{label: "blue", value: "tag_format.html#c"},
{label: "blueviolet (оттенки)", value: "colors.html#violet_hue"},
{label: "blueviolet", value: "tag_format.html#c"},
{label: "bmp", value: "tag_mm.html#images"},
{label: "br", value: "tag_format.html#br"},
{label: "brown (оттенки)", value: "colors.html#brown_hue"},
{label: "brown", value: "tag_format.html#c"},
{label: "burlywood (оттенки)", value: "colors.html#brown_hue"},
{label: "burlywood", value: "tag_format.html#c"},
{label: "c", value: "tag_format.html#c"},
{label: "cadetblue (оттенки)", value: "colors.html#blue_hue"},
{label: "cadetblue", value: "tag_format.html#c"},
{label: "chartreuse (оттенки)", value: "colors.html#green_hue"},
{label: "chartreuse", value: "tag_format.html#c"},
{label: "chocolate (оттенки)", value: "colors.html#brown_hue"},
{label: "chocolate", value: "tag_format.html#c"},
{label: "cmd-line", value: "dsl_comp.html#cmd"},
{label: "code page", value: "langs.html"},
{label: "com", value: "tag_handling.html#com"},
{label: "compiler", value: "dsl_comp.html"},
{label: "CONTENTS_LANGUAGE", value: "directives.html#contents"},
{label: "coral (оттенки)", value: "colors.html#orange_hue"},
{label: "coral", value: "tag_format.html#c"},
{label: "cornflower", value: "tag_format.html#c"},
{label: "cornflowerblue (оттенки)", value: "colors.html#blue_hue"},
{label: "cornsilk (оттенки)", value: "colors.html#brown_hue"},
{label: "cornsilk", value: "tag_format.html#c"},
{label: "crimson (оттенки)", value: "colors.html#red_hue"},
{label: "crimson", value: "tag_format.html#c"},
{label: "cyan", value: "tag_format.html#c"},
{label: "darkblue (оттенки)", value: "colors.html#blue_hue"},
{label: "darkblue", value: "tag_format.html#c"},
{label: "darkcyan (оттенки)", value: "colors.html#green_hue"},
{label: "darkcyan", value: "tag_format.html#c"},
{label: "darkgoldenrod (оттенки)", value: "colors.html#brown_hue"},
{label: "darkgoldenrod", value: "tag_format.html#c"},
{label: "darkgray (оттенки)", value: "colors.html#gray_hue"},
{label: "darkgray", value: "tag_format.html#c"},
{label: "darkgreen (оттенки)", value: "colors.html#green_hue"},
{label: "darkgreen", value: "tag_format.html#c"},
{label: "darkkhaki (оттенки)", value: "colors.html#yellow_hue"},
{label: "darkkhaki", value: "tag_format.html#c"},
{label: "darkmagenta (оттенки)", value: "colors.html#violet_hue"},
{label: "darkmagenta", value: "tag_format.html#c"},
{label: "darkolivegreen (оттенки)", value: "colors.html#green_hue"},
{label: "darkolivegreen", value: "tag_format.html#c"},
{label: "darkorange (оттенки)", value: "colors.html#orange_hue"},
{label: "darkorange", value: "tag_format.html#c"},
{label: "darkorchid (оттенки)", value: "colors.html#violet_hue"},
{label: "darkorchid", value: "tag_format.html#c"},
{label: "darkred (оттенки)", value: "colors.html#red_hue"},
{label: "darkred", value: "tag_format.html#c"},
{label: "darksalmon (оттенки)", value: "colors.html#red_hue"},
{label: "darksalmon", value: "tag_format.html#c"},
{label: "darkseagreen (оттенки)", value: "colors.html#green_hue"},
{label: "darkseagreen", value: "tag_format.html#c"},
{label: "darkslateblue (оттенки)", value: "colors.html#violet_hue"},
{label: "darkslateblue", value: "tag_format.html#c"},
{label: "darkslategray (оттенки)", value: "colors.html#gray_hue"},
{label: "darkslategray", value: "tag_format.html#c"},
{label: "darkturquoise (оттенки)", value: "colors.html#blue_hue"},
{label: "darkturquoise", value: "tag_format.html#c"},
{label: "darkviolet (оттенки)", value: "colors.html#violet_hue"},
{label: "darkviolet", value: "tag_format.html#c"},
{label: "dcx", value: "tag_mm.html#images"},
{label: "deeppink (оттенки)", value: "colors.html#rose_hue"},
{label: "deeppink", value: "tag_format.html#c"},
{label: "deepskyblue (оттенки)", value: "colors.html#blue_hue"},
{label: "deepskyblue", value: "tag_format.html#c"},
{label: "dimgray (оттенки)", value: "colors.html#gray_hue"},
{label: "dimgray", value: "tag_format.html#c"},
{label: "directives", value: "directives.html"},
{label: "dodgerblue (оттенки)", value: "colors.html#blue_hue"},
{label: "dodgerblue", value: "tag_format.html#c"},
{label: "DSL", value: "dsl.html"},
{label: "DSL Compiler", value: "dsl_comp.html"},
{label: "emf", value: "tag_mm.html#images"},
{label: "ex", value: "tag_handling.html#ex"},
{label: "firebrick (оттенки)", value: "colors.html#red_hue"},
{label: "firebrick", value: "tag_format.html#c"},
{label: "floralwhite (оттенки)", value: "colors.html#white_hue"},
{label: "floralwhite", value: "tag_format.html#c"},
{label: "forestgreen (оттенки)", value: "colors.html#green_hue"},
{label: "forestgreen", value: "tag_format.html#c"},
{label: "fuchsia (основные оттенки)", value: "colors.html#basic_hue"},
{label: "fuchsia", value: "tag_format.html#c"},
{label: "gainsboro (оттенки)", value: "colors.html#gray_hue"},
{label: "gainsboro", value: "tag_format.html#c"},
{label: "ghostwhite (оттенки)", value: "colors.html#white_hue"},
{label: "ghostwhite", value: "tag_format.html#c"},
{label: "gif", value: "tag_mm.html#images"},
{label: "gold (оттенки)", value: "colors.html#yellow_hue"},
{label: "gold", value: "tag_format.html#c"},
{label: "goldenrod (оттенки)", value: "colors.html#brown_hue"},
{label: "goldenrod", value: "tag_format.html#c"},
{label: "gray (основные оттенки)", value: "colors.html#basic_hue"},
{label: "gray (оттенки)", value: "colors.html#gray_hue"},
{label: "gray", value: "tag_format.html#c"},
{label: "green (основные оттенки)", value: "colors.html#basic_hue"},
{label: "green (оттенки)", value: "colors.html#green_hue"},
{label: "green", value: "tag_format.html#c"},
{label: "greenyellow (оттенки)", value: "colors.html#green_hue"},
{label: "greenyellow", value: "tag_format.html#c"},
{label: "GUI компилятора", value: "dsl_comp.html#gui"},
{label: "honeydew (оттенки)", value: "colors.html#white_hue"},
{label: "honeydew", value: "tag_format.html#c"},
{label: "hotpink (оттенки)", value: "colors.html#rose_hue"},
{label: "hotpink", value: "tag_format.html#c"},
{label: "i", value: "tag_format.html#i"},
{label: "icon", value: "dict.html#bmp"},
{label: "ICON_FILE", value: "directives.html#icon"},
{label: "images", value: "tag_mm.html#images"},
{label: "INCLUDE", value: "directives.html#include"},
{label: "INDEX_LANGUAGE", value: "directives.html#index"},
{label: "indianred (оттенки)", value: "colors.html#red_hue"},
{label: "indianred", value: "tag_format.html#c"},
{label: "indigo (оттенки)", value: "colors.html#violet_hue"},
{label: "indigo", value: "tag_format.html#c"},
{label: "ISO 639-1", value: "langs.html"},
{label: "ISO 639-2", value: "langs.html"},
{label: "ISO 639-3", value: "langs.html"},
{label: "ivory (оттенки)", value: "colors.html#white_hue"},
{label: "ivory", value: "tag_format.html#c"},
{label: "jpeg", value: "tag_mm.html#images"},
{label: "jpg", value: "tag_mm.html#images"},
{label: "khaki (оттенки)", value: "colors.html#yellow_hue"},
{label: "khaki", value: "tag_format.html#c"},
{label: "lang", value: "tag_handling.html#lang"},
{label: "LANGUAGE", value: "directives.html#lang"},
{label: "lavender (оттенки)", value: "colors.html#violet_hue"},
{label: "lavender", value: "tag_format.html#c"},
{label: "lavenderblush (оттенки)", value: "colors.html#white_hue"},
{label: "lavenderblush", value: "tag_format.html#c"},
{label: "lawngreen (оттенки)", value: "colors.html#green_hue"},
{label: "lawngreen", value: "tag_format.html#c"},
{label: "LCID", value: "langs.html"},
{label: "lemonchiffon (оттенки)", value: "colors.html#yellow_hue"},
{label: "lemonchiffon", value: "tag_format.html#c"},
{label: "lightblue (оттенки)", value: "colors.html#blue_hue"},
{label: "lightblue", value: "tag_format.html#c"},
{label: "lightcoral (оттенки)", value: "colors.html#red_hue"},
{label: "lightcoral", value: "tag_format.html#c"},
{label: "lightcyan (оттенки)", value: "colors.html#blue_hue"},
{label: "lightcyan", value: "tag_format.html#c"},
{label: "lightgoldenrodyellow (оттенки)", value: "colors.html#yellow_hue"},
{label: "lightgoldenrodyellow", value: "tag_format.html#c"},
{label: "lightgreen (оттенки)", value: "colors.html#green_hue"},
{label: "lightgreen", value: "tag_format.html#c"},
{label: "lightgrey (оттенки)", value: "colors.html#gray_hue"},
{label: "lightgrey", value: "tag_format.html#c"},
{label: "lightpink (оттенки)", value: "colors.html#rose_hue"},
{label: "lightpink", value: "tag_format.html#c"},
{label: "lightsalmon (оттенки)", value: "colors.html#red_hue"},
{label: "lightsalmon", value: "tag_format.html#c"},
{label: "lightseagreen (оттенки)", value: "colors.html#green_hue"},
{label: "lightseagreen", value: "tag_format.html#c"},
{label: "lightskyblue (оттенки)", value: "colors.html#blue_hue"},
{label: "lightskyblue", value: "tag_format.html#c"},
{label: "lightslategray (оттенки)", value: "colors.html#gray_hue"},
{label: "lightslategray", value: "tag_format.html#c"},
{label: "lightsteelblue (оттенки)", value: "colors.html#blue_hue"},
{label: "lightsteelblue", value: "tag_format.html#c"},
{label: "lightyellow (оттенки)", value: "colors.html#yellow_hue"},
{label: "lightyellow", value: "tag_format.html#c"},
{label: "lime (основные оттенки)", value: "colors.html#basic_hue"},
{label: "lime (оттенки)", value: "colors.html#green_hue"},
{label: "lime", value: "tag_format.html#c"},
{label: "limegreen (оттенки)", value: "colors.html#green_hue"},
{label: "limegreen", value: "tag_format.html#c"},
{label: "linen (оттенки)", value: "colors.html#white_hue"},
{label: "linen", value: "tag_format.html#c"},
{label: "m", value: "tag_format.html#m"},
{label: "m0", value: "tag_format.html#m"},
{label: "m1", value: "tag_format.html#m"},
{label: "m2", value: "tag_format.html#m"},
{label: "m3", value: "tag_format.html#m"},
{label: "m4", value: "tag_format.html#m"},
{label: "m5", value: "tag_format.html#m"},
{label: "m6", value: "tag_format.html#m"},
{label: "m7", value: "tag_format.html#m"},
{label: "m8", value: "tag_format.html#m"},
{label: "m9", value: "tag_format.html#m"},
{label: "magenta", value: "tag_format.html#c"},
{label: "maroon (основные оттенки)", value: "colors.html#basic_hue"},
{label: "maroon (оттенки)", value: "colors.html#brown_hue"},
{label: "maroon", value: "tag_format.html#c"},
{label: "mediumaquamarine (оттенки)", value: "colors.html#green_hue"},
{label: "mediumaquamarine", value: "tag_format.html#c"},
{label: "mediumblue (оттенки)", value: "colors.html#blue_hue"},
{label: "mediumblue", value: "tag_format.html#c"},
{label: "mediumorchid (оттенки)", value: "colors.html#violet_hue"},
{label: "mediumorchid", value: "tag_format.html#c"},
{label: "mediumpurple (оттенки)", value: "colors.html#violet_hue"},
{label: "mediumpurple", value: "tag_format.html#c"},
{label: "mediumseagreen (оттенки)", value: "colors.html#green_hue"},
{label: "mediumseagreen", value: "tag_format.html#c"},
{label: "mediumslateblue (оттенки)", value: "colors.html#blue_hue"},
{label: "mediumslateblue", value: "tag_format.html#c"},
{label: "mediumspringgreen (оттенки)", value: "colors.html#green_hue"},
{label: "mediumspringgreen", value: "tag_format.html#c"},
{label: "mediumturquoise (оттенки)", value: "colors.html#blue_hue"},
{label: "mediumturquoise", value: "tag_format.html#c"},
{label: "mediumvioletred (оттенки)", value: "colors.html#rose_hue"},
{label: "mediumvioletred", value: "tag_format.html#c"},
{label: "midnightblue (оттенки)", value: "colors.html#blue_hue"},
{label: "midnightblue", value: "tag_format.html#c"},
{label: "mintcream (оттенки)", value: "colors.html#white_hue"},
{label: "mintcream", value: "tag_format.html#c"},
{label: "mistyrose (оттенки)", value: "colors.html#white_hue"},
{label: "mistyrose", value: "tag_format.html#c"},
{label: "moccasin (оттенки)", value: "colors.html#yellow_hue"},
{label: "moccasin", value: "tag_format.html#c"},
{label: "mp3", value: "tag_mm.html#sound"},
{label: "mp4", value: "tag_mm.html#movie"},
{label: "NAME", value: "directives.html#name"},
{label: "navajowhite (оттенки)", value: "colors.html#brown_hue"},
{label: "navajowhite", value: "tag_format.html#c"},
{label: "navy (основные оттенки)", value: "colors.html#basic_hue"},
{label: "navy (оттенки)", value: "colors.html#blue_hue"},
{label: "navy", value: "tag_format.html#c"},
{label: "oldlace (оттенки)", value: "colors.html#white_hue"},
{label: "oldlace", value: "tag_format.html#c"},
{label: "olive (основные оттенки)", value: "colors.html#basic_hue"},
{label: "olive (оттенки)", value: "colors.html#green_hue"},
{label: "olive", value: "tag_format.html#c"},
{label: "olivedrab (оттенки)", value: "colors.html#green_hue"},
{label: "olivedrab", value: "tag_format.html#c"},
{label: "orange (оттенки)", value: "colors.html#orange_hue"},
{label: "orange", value: "tag_format.html#c"},
{label: "orangered (оттенки)", value: "colors.html#orange_hue"},
{label: "orangered", value: "tag_format.html#c"},
{label: "orchid (оттенки)", value: "colors.html#violet_hue"},
{label: "orchid", value: "tag_format.html#c"},
{label: "p", value: "tag_struct.html#p"},
{label: "palegoldenrod (оттенки)", value: "colors.html#yellow_hue"},
{label: "palegoldenrod", value: "tag_format.html#c"},
{label: "palegreen (оттенки)", value: "colors.html#green_hue"},
{label: "palegreen", value: "tag_format.html#c"},
{label: "paleturquoise (оттенки)", value: "colors.html#blue_hue"},
{label: "paleturquoise", value: "tag_format.html#c"},
{label: "palevioletred (оттенки)", value: "colors.html#rose_hue"},
{label: "palevioletred", value: "tag_format.html#c"},
{label: "papayawhip (оттенки)", value: "colors.html#yellow_hue"},
{label: "papayawhip", value: "tag_format.html#c"},
{label: "pcx", value: "tag_mm.html#images"},
{label: "peachpuff (оттенки)", value: "colors.html#yellow_hue"},
{label: "peachpuff", value: "tag_format.html#c"},
{label: "peru (оттенки)", value: "colors.html#brown_hue"},
{label: "peru", value: "tag_format.html#c"},
{label: "pictures", value: "tag_mm.html#images"},
{label: "pink (оттенки)", value: "colors.html#rose_hue"},
{label: "pink", value: "tag_format.html#c"},
{label: "plum (оттенки)", value: "colors.html#violet_hue"},
{label: "plum", value: "tag_format.html#c"},
{label: "png", value: "tag_mm.html#images"},
{label: "powderblue (оттенки)", value: "colors.html#blue_hue"},
{label: "powderblue", value: "tag_format.html#c"},
{label: "preprocessor commands", value: "directives.html"},
{label: "preprocessor directives", value: "directives.html"},
{label: "preview", value: "tag_mm.html#preview"},
{label: "purple (основные оттенки)", value: "colors.html#basic_hue"},
{label: "purple (оттенки)", value: "colors.html#violet_hue"},
{label: "purple", value: "tag_format.html#c"},
{label: "red (основные оттенки)", value: "colors.html#basic_hue"},
{label: "red (оттенки)", value: "colors.html#red_hue"},
{label: "red", value: "tag_format.html#c"},
{label: "ref", value: "tag_links.html#ref2"},
{label: "rosybrown (оттенки)", value: "colors.html#brown_hue"},
{label: "rosybrown", value: "tag_format.html#c"},
{label: "royalblue (оттенки)", value: "colors.html#blue_hue"},
{label: "royalblue", value: "tag_format.html#c"},
{label: "s", value: "tag_mm.html#s"},
{label: "saddlebrown (оттенки)", value: "colors.html#brown_hue"},
{label: "saddlebrown", value: "tag_format.html#c"},
{label: "salmon (оттенки)", value: "colors.html#red_hue"},
{label: "salmon", value: "tag_format.html#c"},
{label: "sandybrown (оттенки)", value: "colors.html#brown_hue"},
{label: "sandybrown", value: "tag_format.html#c"},
{label: "seagreen (оттенки)", value: "colors.html#green_hue"},
{label: "seagreen", value: "tag_format.html#c"},
{label: "seashell (оттенки)", value: "colors.html#white_hue"},
{label: "seashell", value: "tag_format.html#c"},
{label: "sienna (оттенки)", value: "colors.html#brown_hue"},
{label: "sienna", value: "tag_format.html#c"},
{label: "silver (основные оттенки)", value: "colors.html#basic_hue"},
{label: "silver (оттенки)", value: "colors.html#gray_hue"},
{label: "silver", value: "tag_format.html#c"},
{label: "skyblue (оттенки)", value: "colors.html#blue_hue"},
{label: "skyblue", value: "tag_format.html#c"},
{label: "slateblue (оттенки)", value: "colors.html#violet_hue"},
{label: "slateblue", value: "tag_format.html#c"},
{label: "slategray (оттенки)", value: "colors.html#gray_hue"},
{label: "slategray", value: "tag_format.html#c"},
{label: "snow (оттенки)", value: "colors.html#white_hue"},
{label: "snow", value: "tag_format.html#c"},
{label: "sound", value: "tag_mm.html#sound"},
{label: "SOURCE_CODE_PAGE", value: "directives.html#source"},
{label: "springgreen (оттенки)", value: "colors.html#green_hue"},
{label: "springgreen", value: "tag_format.html#c"},
{label: "steelblue (оттенки)", value: "colors.html#blue_hue"},
{label: "steelblue", value: "tag_format.html#c"},
{label: "sub", value: "tag_format.html#sub"},
{label: "sup", value: "tag_format.html#sup"},
{label: "t", value: "tag_struct.html#t"},
{label: "tan (оттенки)", value: "colors.html#brown_hue"},
{label: "tan", value: "tag_format.html#c"},
{label: "teal (основные оттенки)", value: "colors.html#basic_hue"},
{label: "teal (оттенки)", value: "colors.html#green_hue"},
{label: "teal", value: "tag_format.html#c"},
{label: "thistle (оттенки)", value: "colors.html#violet_hue"},
{label: "thistle", value: "tag_format.html#c"},
{label: "tif", value: "tag_mm.html#images"},
{label: "tiff", value: "tag_mm.html#images"},
{label: "tomato (оттенки)", value: "colors.html#orange_hue"},
{label: "tomato", value: "tag_format.html#c"},
{label: "trn", value: "tag_handling.html#trn"},
{label: "trn1", value: "tag_handling.html#trn1"},
{label: "trs", value: "tag_handling.html#trs"},
{label: "turquoise (оттенки)", value: "colors.html#blue_hue"},
{label: "turquoise", value: "tag_format.html#c"},
{label: "u", value: "tag_format.html#u"},
{label: "url", value: "tag_links.html#url"},
{label: "video", value: "tag_mm.html#video"},
{label: "violet (оттенки)", value: "colors.html#violet_hue"},
{label: "violet", value: "tag_format.html#c"},
{label: "wav", value: "tag_mm.html#sound"},
{label: "wheat (оттенки)", value: "colors.html#brown_hue"},
{label: "wheat", value: "tag_format.html#c"},
{label: "white (основные оттенки)", value: "colors.html#basic_hue"},
{label: "white (оттенки)", value: "colors.html#white_hue"},
{label: "white", value: "tag_format.html#c"},
{label: "whitesmoke (оттенки)", value: "colors.html#white_hue"},
{label: "whitesmoke", value: "tag_format.html#c"},
{label: "wmf", value: "tag_mm.html#images"},
{label: "yellow (основные оттенки)", value: "colors.html#basic_hue"},
{label: "yellow (оттенки)", value: "colors.html#yellow_hue"},
{label: "yellow", value: "tag_format.html#c"},
{label: "yellowgreen (оттенки)", value: "colors.html#green_hue"},
{label: "yellowgreen", value: "tag_format.html#c"},
{label: "{ }", value: "tag_service.html#unsort"},
{label: "{", value: "tag_service.html#unsort"},
{label: "}", value: "tag_service.html#unsort"},
{label: "{{ }}", value: "tag_service.html#comm"},
{label: "~", value: "tag_service.html#tilde"},
{label: "аббревиатуры", value: "dict.html#abrv"},
{label: "алфавит", value: "colors.html#colors_abc"},
{label: "алфавитная сортировка", value: "colors.html#colors_abc"},
{label: "альтернативная часть заголовка", value: "tag_service.html#alt"},
{label: "английское наименование", value: "langs.html"},
{label: "аннотация", value: "dict.html#ann"},
{label: "аудио", value: "tag_mm.html#sound"},
{label: "белые тона", value: "colors.html#white_hue"},
{label: "видео", value: "tag_mm.html#movie"},
{label: "внешние ссылки", value: "tag_links.html#url"},
{label: "все команды dsl", value: "tag_list.html"},
{label: "все теги dsl", value: "tag_list.html"},
{label: "вторичное отображение", value: "tag_struct.html#ast"},
{label: "выделение подчёркиванием", value: "tag_format.html#u"},
{label: "выделение цветом", value: "tag_format.html#c"},
{label: "графический интерфейс пользователя", value: "dsl_comp.html#gui"},
{label: "группы оттенков", value: "colors.html#colors_hue"},
{label: "директива #CONTENTS_LANGUAGE", value: "directives.html#contents"},
{label: "директива #ICON_FILE", value: "directives.html#icon"},
{label: "директива #INCLUDE", value: "directives.html#include"},
{label: "директива #INDEX_LANGUAGE", value: "directives.html#index"},
{label: "директива #LANGUAGE", value: "directives.html#lang"},
{label: "директива #NAME", value: "directives.html#name"},
{label: "директива #SOURCE_CODE_PAGE", value: "directives.html#source"},
{label: "директивы предварительной обработки", value: "directives.html"},
{label: "директивы препроцессора", value: "directives.html"},
{label: "жёлтые тона", value: "colors.html#yellow_hue"},
{label: "заголовок статьи", value: "entry.html#headword"},
{label: "звук", value: "tag_mm.html#sound"},
{label: "зелёные тона", value: "colors.html#green_hue"},
{label: "зона вторичного отображения", value: "tag_struct.html#ast"},
{label: "зона комментариев", value: "tag_handling.html#com"},
{label: "зона переводов", value: "tag_handling.html#trn"},
{label: "зона примеров", value: "tag_handling.html#ex"},
{label: "изображения", value: "tag_mm.html#images"},
{label: "иконка", value: "dict.html#bmp"},
{label: "имена файлов словаря", value: "dict.html#names"},
{label: "имя тэга", value: "tag_system.html#main"},
{label: "индексирование в Lingvo", value: "search.html"},
{label: "исключение из зоны индексации", value: "tag_handling.html#trs"},
{label: "картинки", value: "tag_mm.html#images"},
{label: "кодовые страницы ANSI в Windows", value: "langs.html#ansi"},
{label: "коды локалей Microsoft", value: "langs.html#lcid"},
{label: "коды наименований языков", value: "langs.html#iso"},
{label: "команда #", value: "tag_service.html#number"},
{label: "команда ( )", value: "tag_service.html#alt"},
{label: "команда @", value: "tag_struct.html#at"},
{label: "команда \\", value: "tag_service.html#backslash"},
{label: "команда ^", value: "tag_format.html#circ"},
{label: "команда { }", value: "tag_service.html#unsort"},
{label: "команда ~", value: "tag_service.html#tilde"},
{label: "командная строка", value: "dsl_comp.html#cmd"},
{label: "комментарии", value: "tag_handling.html#com"},
{label: "компилятор DSL", value: "dsl_comp.html"},
{label: "коричневые тона", value: "colors.html#brown_hue"},
{label: "красная строка", value: "entry.html#blank_line"},
{label: "красные тона", value: "colors.html#red_hue"},
{label: "крышка", value: "tag_format.html#circ"},
{label: "литерал", value: "tag_system.html#meta_lit"},
{label: "локаль", value: "langs.html#lcid"},
{label: "метасимвол", value: "tag_system.html#meta_lit"},
{label: "метасимволы и литералы", value: "tag_system.html#meta_lit"},
{label: "мультимедиа теги", value: "tag_mm.html"},
{label: "надстрочный индекс", value: "tag_format.html#sup"},
{label: "наименование файлов словаря", value: "dict.html#names"},
{label: "наклонное начертание", value: "tag_format.html#i"},
{label: "наклонный шрифт", value: "tag_format.html#i"},
{label: "недокументированная директива #ICON_FILE", value: "directives.html#icon"},
{label: "недокументированная командная строка", value: "dsl_comp.html#cmd"},
{label: "недокументированные параметры командной строки", value: "dsl_comp.html#cmd"},
{label: "недокументированный тег br", value: "tag_format.html#br"},
{label: "недокументированный тег preview", value: "tag_mm.html#preview"},
{label: "недокументированный тег t", value: "tag_struct.html#t"},
{label: "недокументированный тег trn1", value: "tag_handling.html#trn1"},
{label: "недокументированный тег video", value: "tag_mm.html#video"},
{label: "недокументированный тег транскрипции", value: "tag_struct.html#t"},
{label: "несортируемая часть заголовка", value: "tag_service.html#unsort"},
{label: "о тегах dsl", value: "tag_system.html"},
{label: "о формате dsl", value: "dsl.html#format"},
{label: "о языке dsl", value: "dsl.html#lang"},
{label: "оранжевые тона", value: "colors.html#orange_hue"},
{label: "основной текст", value: "dict.html#dsl"},
{label: "основные тона", value: "colors.html#basic_hue"},
{label: "отбивка", value: "entry.html#blank_line"},
{label: "отступы", value: "tag_format.html#m"},
{label: "оттенки", value: "colors.html#colors_hue"},
{label: "параметры командной строки", value: "dsl_comp.html#cmd"},
{label: "перевод строки", value: "tag_format.html#br"},
{label: "переводы", value: "tag_handling.html#trn"},
{label: "перевёртыш", value: "tag_format.html#circ"},
{label: "перечень тегов и команд dsl", value: "tag_list.html"},
{label: "подзаголовок", value: "tag_struct.html#at"},
{label: "подкарточка", value: "tag_struct.html#at"},
{label: "подстатья", value: "tag_struct.html#at"},
{label: "подстрочный индекс", value: "tag_format.html#sub"},
{label: "подчёркивание", value: "tag_format.html#u"},
{label: "поиск и индексирование в Lingvo", value: "search.html"},
{label: "поисковой обработки теги", value: "tag_handling.html"},
{label: "полный список тегов и команд dsl", value: "tag_list.html"},
{label: "полужирное начертание", value: "tag_format.html#b"},
{label: "полужирный шрифт", value: "tag_format.html#b"},
{label: "пометы", value: "tag_struct.html#p"},
{label: "превью", value: "tag_mm.html#preview"},
{label: "препроцессор", value: "directives.html"},
{label: "примеры", value: "tag_handling.html#ex"},
{label: "решётка", value: "tag_service.html#number"},
{label: "розовые тона", value: "colors.html#rose_hue"},
{label: "серые тона", value: "colors.html#gray_hue"},
{label: "символ экранирования", value: "tag_service.html#backslash"},
{label: "синие тона", value: "colors.html#blue_hue"},
{label: "словарная статья", value: "entry.html#article"},
{label: "словарной структуры теги", value: "tag_struct.html"},
{label: "словарь dsl", value: "dict.html"},
{label: "служебные комментарии", value: "tag_service.html#comm"},
{label: "служебные теги и команды", value: "tag_service.html"},
{label: "сопутствующие сведения", value: "additional.html"},
{label: "сортировка по алфавиту", value: "colors.html#colors_abc"},
{label: "сортировка по группам оттенков", value: "colors.html#colors_hue"},
{label: "сортировка по цветовой гамме (второй способ)", value: "colors.html#colors_gamma2"},
{label: "сортировка по цветовой гамме (первый способ)", value: "colors.html#colors_gamma1"},
{label: "списки языков", value: "langs.html"},
{label: "список аббревиатур", value: "dict.html#abrv"},
{label: "список условных сокращений", value: "dict.html#abrv"},
{label: "ссылки", value: "tag_links.html"},
{label: "статья", value: "entry.html"},
{label: "строение словаря", value: "dict.html"},
{label: "структура словарной статьи", value: "entry.html"},
{label: "тег !trs", value: "tag_handling.html#trs"},
{label: "тег *", value: "tag_struct.html#ast"},
{label: "тег << >>", value: "tag_links.html#ref1"},
{label: "тег b", value: "tag_format.html#b"},
{label: "тег br", value: "tag_format.html#br"},
{label: "тег c", value: "tag_format.html#c"},
{label: "тег com", value: "tag_handling.html#com"},
{label: "тег ex", value: "tag_handling.html#ex"},
{label: "тег i", value: "tag_format.html#i"},
{label: "тег lang", value: "tag_handling.html#lang"},
{label: "тег m", value: "tag_format.html#m"},
{label: "тег p", value: "tag_struct.html#p"},
{label: "тег preview", value: "tag_mm.html#preview"},
{label: "тег ref", value: "tag_links.html#ref2"},
{label: "тег s", value: "tag_mm.html#s"},
{label: "тег sub", value: "tag_format.html#sub"},
{label: "тег sup", value: "tag_format.html#sup"},
{label: "тег t", value: "tag_struct.html#t"},
{label: "тег trn", value: "tag_handling.html#trn"},
{label: "тег trn1", value: "tag_handling.html#trn1"},
{label: "тег u", value: "tag_format.html#u"},
{label: "тег urL", value: "tag_links.html#url"},
{label: "тег video", value: "tag_mm.html#video"},
{label: "тег {{ }}", value: "tag_service.html#comm"},
{label: "тег помет", value: "tag_struct.html#p"},
{label: "тег транскрипции", value: "tag_struct.html#t"},
{label: "тег ударения", value: "tag_format.html#str"},
{label: "теги dsl", value: "tag_system.html"},
{label: "теги мультимедиа", value: "tag_mm.html"},
{label: "теги поисковой обработки", value: "tag_handling.html"},
{label: "теги словарной структуры", value: "tag_struct.html"},
{label: "теги форматирования текста", value: "tag_format.html"},
{label: "тело статьи", value: "entry.html#body"},
{label: "тильда", value: "tag_service.html#tilde"},
{label: "транскрипция", value: "tag_struct.html#t"},
{label: "устройство тегов", value: "tag_system.html#main"},
{label: "файл аббревиатур", value: "dict.html#abrv"},
{label: "файл аннотации", value: "dict.html#ann"},
{label: "файл основного текста", value: "dict.html#dsl"},
{label: "файлы словаря", value: "dict.html#names"},
{label: "фиолетовые тона", value: "colors.html#violet_hue"},
{label: "формат dsl", value: "dsl.html#format"},
{label: "форматирование текста", value: "tag_format.html"},
{label: "цвета dsl", value: "colors.html"},
{label: "цветной текст", value: "tag_format.html#c"},
{label: "цветовая гамма 1", value: "colors.html#colors_gamma1"},
{label: "цветовая гамма 2", value: "colors.html#colors_gamma2"},
{label: "цветовая палитра dsl", value: "colors.html"},
{label: "что такое dsl", value: "dsl.html"},
{label: "экранирование", value: "tag_service.html#backslash"},
{label: "язык dsl", value: "dsl.html#lang"},
{label: "языки", value: "langs.html"},
{label: "языки, поддерживаемые Lingvo", value: "langs.html#supported"},
{label: "языковая разметка", value: "tag_handling.html#lang"},];


$(document).ready(function () {


$( "#searchfield" ).autocomplete({
   source: arr, 
   select: function(event, ui){event.preventDefault(); /*$(this).val("");*/ parent.frames[1].location = ui.item.value;},
   focus: function(event, ui){event.preventDefault();/*$(this).val(ui.item.label);*/}
    
});


});//document ready


